### ISSUE TITLE
On saving domain in Admin, 'Theme field is not valid' error

### ISSUE THREAD

**Issue by balintd** [meshifyiot/carbon-docs#105] opened 2017-11-15 15:26 UTC
I uploaded the following theme object to a domain with an API request:
```
var obj = {
  "theme": {
    "ClientCompanyURL": "https://www.selective.com/",
    "companyLogo": "img/selectiveinsurance.jpg",
    "FAQPage": "faq-selective",
    "SupportPage": "support-selective",
    "deviceLocations": ["Kitchen","Mechanical Room","Office","Stairwell","Basement","Hallway","Entrance/Lobby","Crawl Space","Sanctuary","Baptismal","Restroom/Bathroom","Confessional","Dressing Room"],
    "SignupKeyDescription": " * Your signup key is your 10 digit account number. If you do not know your account number, please contact the Monitoring and Support Center at 1-844-468-1866.",
    "ParticipantionAgreementUrl": "agreement-selective",
    "PhoneNumber": "1-844-468-1866",
    "CompanyName": "Selective Insurance Group, Inc.",
    "wronglocation": "Re-enter your information or contact the Monitoring and Support Center at (844) 468-1866."
  }
}
```

Now I'm trying to edit the domain `https://hsb-test-carbon.meshify.com/admin#domains/edit/27` which has this object attached to it.

When I click save on Admin, I get a `Theme field is not valid` error.

**Comment by psk788** [comment] 2017-11-15 15:33
Perhaps it's the deviceLocations?  Does theming support arrays?

**Comment by MattMadeiro** [comment] 2017-11-15 15:37
I'm thinking the issue is that array you have for the 'deviceLocations' property — our current theme editor doesn't appear to parse it correctly, as evidenced by the blank line here. Validation then fails because the value for that property is an empty string, I think. 
<img width="1260" alt="screen shot 2017-11-15 at 9 32 53 am" src="https://user-images.githubusercontent.com/3777742/32844422-00606d14-c9e8-11e7-838f-a2d8c8037979.png">

The theme editor in the interface is really intended for simple (flat) JSON structures. We're not going to build a more advanced one, as that's a huge time investment we can't afford at the moment. I'll see if we can't better support arrays, though. In the meantime, you'll have to keep using Postman to update that domain.

**Comment by MattMadeiro** [comment] 2017-11-15 15:41
@psk788 @balintd Just to be clear, themes and metadata support whatever the heck you want to throw in them. :) It's just that the theme editor itself can't currently support arrays and nested objects.

**Comment by balintd** [comment] 2017-11-15 15:41
Ok, thanks for the reply. It's not an issue for me, just something I noticed and figured it's a good idea to capture it and discuss.

If those domains will need to be editable from admin in the future, I can just use a string instead of the array and split it on the front-end or something like that.

**Comment by MattMadeiro** [comment] 2017-11-15 15:43
👍 That would make our lives a lot easier. I've created an internal ticket for adding array support and stuff like that, but I can't give any kind of estimate for when it would be available. For now, if you're okay doing a comma-separated string, that should solve all problems. 

I'll go ahead and close this issue now that we have a different internal one, but feel free to reopen it for further conversation or if you notice any other issues.

**Closed by MattMadeiro** 2017-11-15 15:43 UTC
