### ISSUE TITLE
Channel does not appear on Admin->Current Values if user doesn't specify Default value

### ISSUE THREAD

**Issue by willpopski** [meshifyiot/carbon-docs#66] opened 2017-10-17 18:23 UTC
If a channel default is empty (null), then a channel will not show up on current values.

Users expect all channels to show up there, even if the default is empty.

**Comment by willpopski** [comment] 2017-10-17 18:23
Customer reported, ticket 910.

**Comment by Ashtonian** [comment] 2017-10-17 18:51
@willpopski correction to my earlier statement, I did introduce a bug. Had > 1 instead of > 0, this is occurring because the user has one channel with one datapoint... To clarify further the expected behavior for data/current is to always return channels that are defined in the node type even if the default is null. I will add a test to cover this behavior. 

Fix has been deployed. Also that customer likely needs some help as we are getting data on a channel named "temperature_t" not what is currently configured  "temperature".

**Closed** 2017-10-17 18:51 UTC
